### ISSUE TITLE
How to make it

### ISSUE THREAD

**Issue by AGenchev** [nicktrandafil/vcf2csv#1]
I cloned,
went to ./src
made ./build in src, then ran from build cmake ..
and it complains about missing statements in CmakeLists

**Comment by nicktrandafil** [comment]
```
git clone https://github.com/nicktrandafil/vcf2csv.git
cd vcf2csv
mkdir build
cd build
cmake ..
make
```

You should find the produced binary at `./src/vcf2csv`.

You also should make sure Boost is installed in your system.

If you fail to compile please post the cmake and make outputs.
